### ISSUE TITLE
do you announce signedTransaction_staticDeadline?

### ISSUE THREAD

**Issue by mediaprogramer** [evias/nem2-sdk-bugreports#1]
I think that here is `signedTransaction_staticDeadline` 
Is it right?

https://github.com/evias/nem2-sdk-bugreports/blob/a87dc20fec5092ddc02c13508493393a65d4c204/src/UsePrivateNetworkDeadline.ts#L110

**Comment by evias** [comment]
Thank you :blush: :) :)

**Comment by evias** [comment]
after fixing this - both transactions actually work. Solved in [`625e965`](https://github.com/evias/nem2-sdk-bugreports/commit/625e965545b5a823dd3891f4cc38aee1a994fac1)

But this deadline infrastructure problem is being discussed and being worked on in nem2-sdk. 

Thank you for reporting this issue on the code :+1:
